version: 1.0.{build}

# environment variables
environment:
  nodejs_version: "5.0"
  GithubEmail: johnny_reilly@hotmail.com
  GithubUsername: johnnyreilly
  GithubPersonalAccessToken:
    secure: T4M/N+e/baksVoeWoYKPWIpfahOsiSFw/+Zc81VuThZmWEqmrRtgEHUyin0vCWhl

branches:
  only:
    - master

# scripts to run before build
before_build:
- cmd: >-
    npm install

build_script:
- cmd: >-
    npm run build-lib

    npm run build-demo

    npm run test

before_test:
- ps: >-
    ./registerTestResults.ps1

deploy_script:
- ps: ./pushStatic.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:APPVEYOR_REPO_NAME
